import { useNavigate } from 'react-router-dom';

export default function Home() {
  const navigate = useNavigate();
  return (
    <div className="container">
      <div className="hero">
        <h1>
          Learn to <span style={{ color: 'var(--rust)' }}>think</span> in Rust
        </h1>
        <p className="muted" style={{ maxWidth: 620, margin: '0 auto' }}>
          A hybrid learning platform that combines deterministic pedagogy state
          machines with a Retrieval-Augmented knowledge layer grounded in
          <em> The Rust Programming Language</em>. Most tutorials teach syntax —
          this one teaches reasoning.
        </p>
      </div>

      <div className="grid" style={{ marginTop: 24 }}>
        <div className="card">
          <h3>🗺️ Planner Mode</h3>
          <p className="muted">
            Decompose any problem in 11 deterministic steps — inputs, outputs,
            variables, iteration, edge cases — with forced-choice scaffolding,
            before writing a line of Rust.
          </p>
          <button className="btn-primary" onClick={() => navigate('/planner')}>
            Start Planning →
          </button>
        </div>

        <div className="card">
          <h3>🧠 Mentor Mode</h3>
          <p className="muted">
            Understand tricky concepts through a 5-stage Socratic dialogue:
            open question → narrowing → forced choice → concrete anchor →
            transfer check.
          </p>
          <button className="btn-primary" onClick={() => navigate('/mentor')}>
            Ask the Mentor →
          </button>
        </div>

        <div className="card">
          <h3>📊 Dashboard</h3>
          <p className="muted">
            Track which of the 15 core Rust concepts you are learning versus
            have truly mastered (verified by transfer checks).
          </p>
          <button className="btn-primary" onClick={() => navigate('/dashboard')}>
            View Progress →
          </button>
        </div>
      </div>

      <div className="card" style={{ marginTop: 24 }}>
        <h3>How the hybrid architecture works</h3>
        <p className="muted">
          Every question and hint is generated by an LLM (GPT-4o via OpenRouter)
          but <strong>grounded</strong> in the actual book: your query is
          embedded, the most relevant passages are retrieved from a pgvector
          store, and injected into the prompt. The <em>sequence</em> of teaching
          steps is fixed by a deterministic state machine, so the pedagogy stays
          consistent while the content stays accurate.
        </p>
      </div>
    </div>
  );
}
